"""add customer_phone_snap to invoices

Revision ID: 247c0b06a3f2
Revises: b9c0d1e2f3a4
Create Date: 2026-06-29 00:17:42.617522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247c0b06a3f2'
down_revision = 'b9c0d1e2f3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone_snap', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('customer_phone_snap')

    # ### end Alembic commands ###
