"""items per-user with global flag

Revision ID: 796c99df61e4
Revises: e0e9ecd7170e
Create Date: 2026-03-28 00:18:08.553297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796c99df61e4'
down_revision = 'e0e9ecd7170e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('items_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_items_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_item_user_code', ['user_id', 'code'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_item_user_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_items_user_id'))
        batch_op.create_unique_constraint(batch_op.f('items_code_key'), ['code'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('is_global')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
