"""add is_superadmin to users

Revision ID: 83beed7f9517
Revises: 796c99df61e4
Create Date: 2026-03-28 00:40:20.287666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83beed7f9517'
down_revision = '796c99df61e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###
