"""supplier payment nullable billing_name

Revision ID: 8cfdd34e8f1b
Revises: a13e348e0c86
Create Date: 2026-03-29 16:58:59.405965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfdd34e8f1b'
down_revision = 'a13e348e0c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_name', sa.String(length=150), nullable=True))
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('billing_name')

    # ### end Alembic commands ###
