"""add billing_name to customer_payments

Revision ID: a13e348e0c86
Revises: 2f1c250e0160
Create Date: 2026-03-29 16:47:20.671175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13e348e0c86'
down_revision = '2f1c250e0160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_column('billing_name')

    # ### end Alembic commands ###
