"""add missing tables

Revision ID: e0e9ecd7170e
Revises: b4e2f3a1c890
Create Date: 2026-03-28 00:13:07.978859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e9ecd7170e'
down_revision = 'b4e2f3a1c890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_limits_ip_address'), ['ip_address'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_user_id'), ['user_id'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=150), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_number')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_user_id'), ['user_id'], unique=False)

    op.create_table('user_item_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id')
    )
    with op.batch_alter_table('user_item_discounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_item_discounts_user_id'), ['user_id'], unique=False)

    op.create_table('purchase_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('tp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('retail', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disc_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoices_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_password_hash', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('admin_reset_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admin_password_is_temp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin_failed_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_locked_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))
        batch_op.drop_column('admin_locked_until')
        batch_op.drop_column('admin_failed_attempts')
        batch_op.drop_column('admin_password_is_temp')
        batch_op.drop_column('admin_reset_requested_at')
        batch_op.drop_column('admin_password_hash')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))
        batch_op.drop_column('user_id')

    op.drop_table('purchase_lines')
    with op.batch_alter_table('user_item_discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_item_discounts_user_id'))

    op.drop_table('user_item_discounts')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_user_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_user_id'))

    op.drop_table('suppliers')
    op.drop_table('users')
    with op.batch_alter_table('guest_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_limits_ip_address'))

    op.drop_table('guest_limits')
    # ### end Alembic commands ###
