"""add customer_name_snap to invoices

Revision ID: f678cb3ac489
Revises: 55416e9e5812
Create Date: 2026-03-25 02:04:04.604893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f678cb3ac489'
down_revision = '55416e9e5812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name_snap', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('customer_name_snap')

    # ### end Alembic commands ###
